name: Publish to Chrome Store

on:
  push:
    branches:
      - develop
      - feat/deployApp
  pull_request:
    branches: [develop]

jobs:
  deployApp:
    runs-on: ubuntu-latest
    steps:
      - uses: mnao305/chrome-extension-upload@1.1.0
        with:
          # extension is only necessary when updating an existing addon,
          # omitting it will create a new addon
          file-path: './addon.zip'
          extension-id: hogefuga(gnhijpffhbjbchehfipckfpjhmofocla)
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          # optionally specify the visibility of the addon
          # publishTarget: default

