name: Tests

on:
  push:
    branches: 
      - develop 
  pull_request:
    branches: [ develop ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: |
        npm install 
        npm test
  codeCoverage:
    uses: coverallsapp/github-action@master
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }} 