name: Tests

on:
  push:
    branches: 
      - develop 
  pull_request:
    branches: [ develop ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: |
        npm install 
        npm test
  codeCoverage:
    runs-on: ubuntu-latest
    steps:
      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ../../coverage/lcov.info